"""
CardioCare — Explainability Service (Phase 5)
=============================================
Loads the precomputed explainability.json (generated by
scripts/03_precompute_explainability.py) and provides:

  - global feature importance
  - global SHAP values
  - confusion matrix
  - ROC curve data
  - Precision-Recall curve data
  - per-prediction SHAP explanation (computed at request time — fast for XGBoost)

PERFORMANCE NOTE:
  Global explanations are precomputed once and cached here as module-level state.
  Per-prediction SHAP uses XGBoost's fast TreeExplainer — typically < 50 ms.

DISCLAIMER:
  Feature contributions represent model behavior, not medical causation.
  This system is NOT a medical diagnostic tool.
"""

import json
import logging
import warnings
from pathlib import Path
from typing import Dict, Any, List, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)
warnings.filterwarnings("ignore")

# ── Paths ─────────────────────────────────────────────────────────────────────
MODELS_DIR       = Path(__file__).resolve().parent.parent.parent.parent / "ml" / "saved_models"
EXPLAINABILITY_PATH = MODELS_DIR / "explainability.json"


class ExplainabilityService:
    def __init__(self):
        self._data: Optional[Dict[str, Any]] = None
        self._shap_explainer = None
        self._scaler = None
        self._feature_cols: List[str] = []
        self._load()

    def _load(self):
        """Load precomputed explainability data and prepare SHAP for per-prediction use."""
        if not EXPLAINABILITY_PATH.exists():
            logger.warning(
                "explainability.json not found. "
                "Run: python scripts/03_precompute_explainability.py"
            )
            return

        with open(EXPLAINABILITY_PATH, "r", encoding="utf-8") as f:
            self._data = json.load(f)

        self._feature_cols = [
            row["feature"] for row in self._data.get("feature_importance", [])
        ]
        # Sort feature_cols back to the original training order so SHAP input aligns
        # (precomputed list is sorted by importance — need original order for transform)
        TRAIN_ORDER = [
            "age_years", "gender", "height", "weight", "bmi",
            "systolic_bp", "diastolic_bp", "cholesterol", "glucose",
            "smoking", "alcohol", "physical_activity"
        ]
        self._feature_cols_ordered = TRAIN_ORDER

        # Load scaler + model for per-prediction SHAP
        try:
            import joblib, shap
            from app.services.prediction_service import MODEL_PATH, SCALER_PATH

            model  = joblib.load(MODEL_PATH)
            scaler = joblib.load(SCALER_PATH)
            self._scaler          = scaler
            self._shap_explainer  = shap.TreeExplainer(model)
            logger.info("SHAP TreeExplainer initialised for per-prediction explanations.")
        except Exception as e:
            logger.warning(f"Per-prediction SHAP not available: {e}")

        logger.info("ExplainabilityService loaded successfully.")

    def is_ready(self) -> bool:
        return self._data is not None

    # ── Global explanations (cheap — just reads the cached JSON) ──────────────

    def get_feature_importance(self) -> List[Dict[str, Any]]:
        """Return model-level feature importance sorted descending."""
        if not self.is_ready():
            return []
        return self._data.get("feature_importance", [])

    def get_global_shap(self) -> Dict[str, Any]:
        """Return global mean |SHAP| values (precomputed on 2000-sample subset)."""
        if not self.is_ready():
            return {}
        return {
            "method":      "TreeExplainer (sampled, n=2000)",
            "features":    self._data.get("global_shap", []),
            "available":   self._data.get("shap_available", False),
        }

    def get_global_explainability(self) -> Dict[str, Any]:
        """Full global explainability payload for the dashboard endpoint."""
        if not self.is_ready():
            return {"status": "not_ready"}
        return {
            "model_name":         self._data.get("model_name"),
            "model_version":      self._data.get("model_version"),
            "generated_at":       self._data.get("generated_at"),
            "feature_importance": self._data.get("feature_importance", []),
            "global_shap":        self._data.get("global_shap", []),
            "shap_available":     self._data.get("shap_available", False),
            "feature_list":       self._feature_cols_ordered,
            "disclaimer":         self._data.get("disclaimer", ""),
        }

    def get_confusion_matrix(self) -> Dict[str, Any]:
        """Return confusion matrix from the training evaluation dataset."""
        if not self.is_ready():
            return {}
        # Stored in explainability.json → loaded from model_metadata.json during precompute
        # We read it from prediction_service.metadata directly to avoid duplication
        try:
            from app.services.prediction_service import prediction_service
            cm = prediction_service.metadata.get("metrics", {}).get("confusion_matrix", [])
            if cm and len(cm) == 2:
                return {
                    "true_negative":  cm[0][0],
                    "false_positive": cm[0][1],
                    "false_negative": cm[1][0],
                    "true_positive":  cm[1][1],
                    "source": "model evaluation on held-out test set (20%)",
                }
        except Exception as e:
            logger.error(f"Confusion matrix read error: {e}")
        return {}

    def get_roc_curve(self) -> Dict[str, Any]:
        """Return precomputed ROC curve data."""
        if not self.is_ready():
            return {}
        return self._data.get("roc_curve", {})

    def get_precision_recall(self) -> Dict[str, Any]:
        """Return precomputed Precision-Recall curve data."""
        if not self.is_ready():
            return {}
        return self._data.get("precision_recall", {})

    # ── Per-prediction SHAP ───────────────────────────────────────────────────

    def explain_prediction(
        self, features_dict: Dict[str, float], top_n: int = 5
    ) -> Dict[str, Any]:
        """
        Compute SHAP values for a single prediction.

        Returns:
          - explanation: list of {feature, value, contribution, direction}
          - top_positive_contributors: top N features pushing toward CVD class
          - top_negative_contributors: top N features pushing away from CVD class

        DISCLAIMER: contributions represent model behaviour, not medical causation.
        """
        if self._shap_explainer is None or self._scaler is None:
            return {
                "available": False,
                "reason": "SHAP explainer not initialised",
            }

        try:
            # Build input array in training order
            input_array = np.array([
                [features_dict[f] for f in self._feature_cols_ordered]
            ])
            X_scaled = self._scaler.transform(input_array)
            X_df     = pd.DataFrame(X_scaled, columns=self._feature_cols_ordered)

            shap_vals = self._shap_explainer.shap_values(X_df)  # shape (1, 12)
            shap_row  = shap_vals[0]  # 12 values

            explanation = [
                {
                    "feature":      feat,
                    "value":        float(round(features_dict[feat], 4)),
                    "contribution": float(round(float(sv), 6)),
                    "direction":    "toward_positive_class" if sv > 0 else "toward_negative_class",
                }
                for feat, sv in zip(self._feature_cols_ordered, shap_row)
            ]

            # Sort by absolute contribution
            explanation_sorted = sorted(explanation, key=lambda x: abs(x["contribution"]), reverse=True)

            positive = [e for e in explanation_sorted if e["direction"] == "toward_positive_class"][:top_n]
            negative = [e for e in explanation_sorted if e["direction"] == "toward_negative_class"][:top_n]

            return {
                "available":                 True,
                "method":                    "SHAP TreeExplainer",
                "explanation":               explanation_sorted,
                "top_positive_contributors": positive,
                "top_negative_contributors": negative,
                "disclaimer": (
                    "Feature contributions represent model behaviour, not medical causation. "
                    "Higher contribution toward predicted class does not imply that feature caused the condition."
                ),
            }

        except Exception as e:
            logger.error(f"Per-prediction SHAP error: {e}")
            return {"available": False, "reason": str(e)}


# Singleton instance — loaded once at server startup
explainability_service = ExplainabilityService()
